#############################################################################################################################################
# This script use as input the StatResults.txt generated by GP120VariantComputer.py to produced distribution plots for                      #
# Diversity, Shannon entropy, Complexity and Number of haplotypes. For each one of these measure a  pdf file is created in which one may   #
# compare the distribution for Recent and Chronic HIV sample in every choosen region of gp120.                                              #
#                                                                                                                                           #
# To run it, simply enter the following command line in terminal                                                                            #
# Rscript MakePlot.R "Complexity-Shannon-Diversity-Number of haplotypes" "across gp120 region" StatResults.txt                            #
#                                                                                                                                           #
#############################################################################################################################################

#Read the arguments
args=commandArgs(TRUE)

#Make a list of arguments
param_list=list(ev_param=args[1],titre=args[2],data=args[3])

#Load libraries
library(extrafont)
library(ggplot2)
library(data.table)


#####################################################################################
# Function used to build distribution plots from of the evolution parameter values. #
# <evol_param> is Diversity, Compexity, Shannon or Number of haplotypes             #
# <Title> is the title of the ggplot                                                #
# <data_source> is the statistic file                                               #   
#####################################################################################
plot_f=function(evol_param,Title,data_source){

	print(evol_param)	
        
        #Read the statistic file
	my_data=read.table(data_source,header=T)
	my_data=data.table(my_data)

        #Column to use in the statistic file according to evol_param. Color
	#of the curves is depending of the Type column which is treated as factor (RECENT and CHRONIC)
	if(evol_param == "Complexity"){
		g=ggplot(my_data,aes(x=Complexity,color=Type))
	}
	else if(evol_param == "Diversity"){
		g=ggplot(my_data,aes(x=Diversity,color=Type))
	}
	else if(evol_param == "Number of haplotypes"){
		g=ggplot(my_data,aes(x=Nb_haplotype,color=Type))

	}
	else{
		g=ggplot(my_data,aes(x=Shannon,color=Type))
	}
	
	g=g+geom_density(data=subset(my_data,Type=="RECENT"),alpha=0.9)
	g=g+geom_density(data=subset(my_data,Type=="CHRONIC"),alpha=0.9)
        #Distribution plots are arranged in three column with fixed y scale
	g=g+facet_wrap( ~ Region,ncol=3,scales="free_x")
        #Label of the x axis
	g=g+xlab(evol_param)
        #Label of the y axis
	g=g+ylab("Frequency")
        #Title
	g=g+ggtitle(paste(evol_param,"across the gp120 regions",sep=" "))
	g=g+scale_color_discrete(name="")
        #Themes
	g=g+theme(axis.text = element_text(size=7,face="bold"),axis.text.x=element_text(angle=45,hjust=1),text=element_text(family="FreeSerif"))
	g=g+theme(axis.title = element_text(size=11,face="bold",family="FreeSerif"),strip.text = element_text(face="bold"))
	g=g+theme(plot.title = element_text(size=15,face="bold",family="FreeSerif",hjust=0.5,vjust=0.8))


        #Print the plots
	print(g)
        #Save them as pdf file
	ggsave(paste(evol_param,".pdf",sep=""), width=16.68, height=22.225, units="cm",dpi=300)
	
}

#Title suffix according to the evolution parameter
title_suffix=param_list$titre


#Do the following for each of the three evolution parameters
for(i in strsplit(param_list$ev_param,"-")[[1]]){
        
        #Print out
	print(paste("Make plot for",i,sep=":"))	
        
        #Build the title
	if(i=="Shannon"){
		title=paste("Sahnnon index",title_suffix)
	}
	else if(i=="Diversity"){
		title=paste("Nucleotide diversity",title_suffix)
	}

	else if(i=="Number of haplotypes"){
		title=paste("Number of haplotypes",title_suffix)
	}
        else{
		title=paste(i,title_suffix)

	}
        
        #Build the distribution plots
	plot_f(i,title,param_list$data)
	
}


warnings()
